---
driver:
  name: docker
  use_sudo: false
  use_internal_docker_network: true

# provisioner:
#   name: ansible_playbook
#   hosts: localhost
#   no_proxy: localhost,127.0.0.1
#   # requirements_path: requirements.yml
#   require_ansible_repo: true
#   ansible_verbose: true
#   ansible_verbosity: 2
#   ansible_diff: true
#   require_chef_for_busser: false
#   ssh_known_hosts:
#     - github.com
provisioner:
  ansible_connection: local
  ansible_host_key_checking: false
  ansible_version: latest
  custom_pre_play_command: sudo chown -R kitchen:kitchen /home/kitchen/.ansible
  name: ansible_playbook
  hosts: test-kitchen
  #idempotency_test: true
  require_ansible_repo: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  role_name: {{cookiecutter.role_name}}

platforms:
  - name: centos-6

verifier:
  name: inspec
  sudo_path: true

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: site.yml

transport:
  max_ssh_sessions: 6
  forward_agent: true
